(function(){
  const DELIVERY_CATEGORY='__ENTREGA__';
  const DEFAULTS=[['Montese',15],['Parangaba',10],['Maraponga',10],['Pici',10],['Bela Vista',8],['Demócrito Rocha',8],['Henrique Jorge',8],['Vila Pery',6],['Manoel Sátiro',6],['Jatobá',6],['Pq. São José',6],['Pq. Santa Rosa',6],['Canindezinho',6],['Mondubim',7],['Conjunto Esperança',7],['Conjunto Ceará',5],['João XXIII',6],['Granja Lisboa',4],['Bom Sucesso',6],['Granja Portugal',4],['Bom Jardim',4],['Siqueira',6],['Benfica',20],['Centro',20],['Auta Nunes',12],['Quintino Cunha',15],['Barra do Ceará',25],['Genibaú',10],['Passaré',15]];
  let editingArea='';
  const $=s=>document.querySelector(s);
  const esc2=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function areaProducts(){return (window.products||products||[]).filter(p=>String(p.categoria||'')===DELIVERY_CATEGORY)}
  function merged(){const map=new Map(DEFAULTS.map(([nome,fee])=>[nome.toLocaleLowerCase('pt-BR'),{id:'',nome,preco:fee,ativo:true,default:true}]));areaProducts().forEach(p=>map.set(String(p.nome||'').toLocaleLowerCase('pt-BR'),p));return [...map.values()].sort((a,b)=>String(a.nome).localeCompare(String(b.nome),'pt-BR'))}
  function renderAreas(){const box=$('#deliveryAreasTable');if(!box)return;const rows=merged();box.innerHTML=`<div class="delivery-head"><div><h2>Bairros e taxas de entrega</h2><p>Cadastre ou altere o valor da entrega. A mudança chega ao app do cliente automaticamente.</p></div><button id="newAreaBtn" class="primary">+ Novo bairro</button></div><div class="delivery-form" id="areaForm" hidden><input id="areaName" placeholder="Nome do bairro"><input id="areaFee" type="number" step="0.01" min="0" placeholder="Taxa R$"><label><input id="areaActive" type="checkbox" checked> Disponível</label><button id="saveAreaBtn" class="primary">Salvar</button><button id="cancelAreaBtn">Cancelar</button><small id="areaMsg"></small></div><div class="table-wrap"><table><thead><tr><th>Bairro</th><th>Taxa</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows.map(a=>`<tr><td><strong>${esc2(a.nome)}</strong>${a.default&&!a.id?'<br><small>Padrão atual</small>':''}</td><td><strong>${money(a.preco)}</strong></td><td><span class="status-pill ${a.ativo!==false?'status-on':'status-off'}">${a.ativo!==false?'● DISPONÍVEL':'● INDISPONÍVEL'}</span></td><td><div class="row-actions"><button data-area-edit="${esc2(a.nome)}">Editar</button><button class="save-row" data-area-toggle="${esc2(a.nome)}">${a.ativo!==false?'Pausar':'Ativar'}</button></div></td></tr>`).join('')}</tbody></table></div>`;
    $('#newAreaBtn').onclick=()=>openArea();$('#cancelAreaBtn').onclick=closeArea;$('#saveAreaBtn').onclick=saveArea;
    document.querySelectorAll('[data-area-edit]').forEach(b=>b.onclick=()=>openArea(merged().find(a=>a.nome===b.dataset.areaEdit)));
    document.querySelectorAll('[data-area-toggle]').forEach(b=>b.onclick=()=>toggleArea(merged().find(a=>a.nome===b.dataset.areaToggle)));
  }
  function openArea(a){editingArea=a?.id||'';$('#areaForm').hidden=false;$('#areaName').value=a?.nome||'';$('#areaFee').value=Number(a?.preco||0);$('#areaActive').checked=a? a.ativo!==false:true;$('#areaMsg').textContent='';$('#areaName').focus()}
  function closeArea(){$('#areaForm').hidden=true;editingArea=''}
  function slugArea(s){return 'entrega-'+String(s||'bairro').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}
  async function saveArea(){const nome=$('#areaName').value.trim(),fee=Number($('#areaFee').value);if(!nome)return $('#areaMsg').textContent='Informe o bairro.';if(!Number.isFinite(fee)||fee<0)return $('#areaMsg').textContent='Informe uma taxa válida.';const existing=merged().find(a=>a.nome.toLocaleLowerCase('pt-BR')===nome.toLocaleLowerCase('pt-BR'));const id=editingArea||existing?.id||slugArea(nome);$('#saveAreaBtn').disabled=true;$('#areaMsg').textContent='Salvando...';try{const p={id,nome,categoria:DELIVERY_CATEGORY,preco:fee,unidade:'taxa',ativo:$('#areaActive').checked,descricao:'Taxa de entrega por bairro',imagem:'',promocao:false,preco_promocional:0,promo_inicio:'',promo_fim:''};const d=await apiPost({action:existing?.id||editingArea?'updateProduct':'createProduct',pin:adminPin,product:p});if(!d.ok)throw new Error(d.error||'Erro ao salvar');await loadProducts();renderAreas();closeArea()}catch(e){$('#areaMsg').textContent='Erro: '+e.message}finally{$('#saveAreaBtn').disabled=false}}
  async function toggleArea(a){const p={id:a.id||slugArea(a.nome),nome:a.nome,categoria:DELIVERY_CATEGORY,preco:Number(a.preco||0),unidade:'taxa',ativo:a.ativo===false,descricao:'Taxa de entrega por bairro',imagem:'',promocao:false,preco_promocional:0,promo_inicio:'',promo_fim:''};const d=await apiPost({action:a.id?'updateProduct':'createProduct',pin:adminPin,product:p});if(!d.ok)return alert(d.error||'Erro ao atualizar bairro');await loadProducts();renderAreas()}
  function installTab(){const nav=document.querySelector('.admin-tabs');if(!nav||document.querySelector('[data-tab="delivery"]'))return;const b=document.createElement('button');b.dataset.tab='delivery';b.textContent='Bairros e entrega';nav.appendChild(b);const section=document.createElement('section');section.id='tab-delivery';section.className='tab-panel';section.innerHTML='<div id="deliveryAreasTable"></div>';nav.parentNode.appendChild(section);b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x===section));renderAreas()};}
  const originalRenderProducts=window.renderProducts||renderProducts;
  window.renderProducts=renderProducts=function(){const all=products;products=all.filter(p=>String(p.categoria||'')!==DELIVERY_CATEGORY);try{originalRenderProducts()}finally{products=all}if(document.querySelector('#tab-delivery.active'))renderAreas()};
  function addStyles(){const st=document.createElement('style');st.textContent='.delivery-head{display:flex;justify-content:space-between;gap:16px;align-items:center;margin-bottom:18px}.delivery-head h2{margin:0 0 5px}.delivery-head p{margin:0;color:#765b52}.delivery-form{display:grid;grid-template-columns:minmax(180px,2fr) minmax(120px,1fr) auto auto auto;gap:10px;align-items:center;padding:14px;background:#f8f1ee;border:1px solid #eadbd5;border-radius:14px;margin-bottom:18px}.delivery-form input{padding:12px;border:1px solid #decfc9;border-radius:10px}.delivery-form small{grid-column:1/-1}@media(max-width:700px){.delivery-head{align-items:flex-start;flex-direction:column}.delivery-form{grid-template-columns:1fr}.delivery-form small{grid-column:auto}}';document.head.appendChild(st)}
  document.addEventListener('DOMContentLoaded',()=>{addStyles();installTab()});
})();