(function(){
  let lastOrders=[];
  const moneyBR=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
  const safe=s=>String(s??'');
  async function ensurePdf(){if(window.jspdf?.jsPDF)return true;return await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';s.onload=()=>resolve(!!window.jspdf?.jsPDF);s.onerror=reject;document.head.appendChild(s)})}
  async function logoData(){try{const src=window.APP_CONFIG?.OFFICIAL_LOGO_URL||'./logo-oficial.jpg';return await new Promise((res,rej)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>{const c=document.createElement('canvas');c.width=c.height=400;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,400,400);x.drawImage(i,0,0,400,400);res(c.toDataURL('image/jpeg',.9))};i.onerror=rej;i.src=src})}catch(e){return''}}
  function split(doc,t,w){return doc.splitTextToSize(safe(t),w)}
  async function makeOrderPdf(o){if(!(await ensurePdf()))throw new Error('Gerador de PDF indisponível');const {jsPDF}=window.jspdf;const doc=new jsPDF({unit:'mm',format:'a4'});const red=[150,0,0],dark=[35,20,18],logo=await logoData();doc.setFillColor(...red);doc.rect(0,0,210,42,'F');if(logo)try{doc.addImage(logo,'JPEG',9,4,34,34)}catch(e){}doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(17);doc.text('ATACADÃO DA CARNE O PEITICA',49,13);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text('Rua Edison Martins, 530 - Fortaleza/CE',49,21);doc.text('WhatsApp: (85) 98962-6829',49,27);doc.setFont('helvetica','bold');doc.text(`PEDIDO ${safe(o.id)}`,49,35);let y=52;const section=t=>{doc.setTextColor(...dark);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text(t,14,y);doc.setDrawColor(...red);doc.line(14,y+3,196,y+3);y+=10};section('DADOS DO CLIENTE');doc.setFontSize(10);[['Cliente',o.cliente],['WhatsApp',o.telefone],['Recebimento',o.recebimento==='entrega'?'ENTREGA':'RETIRADA NA LOJA'],['Data',o.data||o.criado_em||''],['Status',o.status||'NOVO'],['Pagamento',o.forma_pagamento||o.pagamento||'—']].forEach(([a,b])=>{doc.setFont('helvetica','bold');doc.text(a+':',14,y);doc.setFont('helvetica','normal');doc.text(safe(b||'—'),50,y);y+=6});if(o.recebimento==='entrega'){y+=3;section('DADOS DA ENTREGA');[['Bairro',o.bairro],['Taxa',moneyBR(o.taxa_entrega)],['Endereço',o.endereco],['Referência',o.referencia]].forEach(([a,b])=>{if(!b)return;doc.setFont('helvetica','bold');doc.text(a+':',14,y);doc.setFont('helvetica','normal');const ls=split(doc,b,140);doc.text(ls,50,y);y+=Math.max(6,ls.length*5)});if(o.localizacao){doc.setTextColor(...red);doc.setFont('helvetica','bold');doc.textWithLink('ABRIR ROTA NO GOOGLE MAPS',14,y,{url:o.localizacao});doc.setTextColor(...dark);y+=9}}
    const itens=Array.isArray(o.itens)?o.itens:[];if(itens.length){section('ITENS DO PEDIDO');itens.forEach((i,n)=>{if(y>250){doc.addPage();y=20}doc.setFont('helvetica','bold');doc.text(`${n+1}. ${safe(i.nome)}`,14,y);doc.setFont('helvetica','normal');const qtd=i.unidade==='kit'?`${i.quantidade} kit(s)`:`${i.quantidade} g`;doc.text(qtd,145,y,{align:'right'});doc.setFont('helvetica','bold');doc.text(moneyBR(i.subtotal),196,y,{align:'right'});y+=6;if(i.observacao){doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text(split(doc,'Obs.: '+i.observacao,175),18,y);y+=6}doc.setFontSize(10)})}
    if(o.observacoes){y+=3;section('OBSERVAÇÕES');doc.setFont('helvetica','normal');doc.setFontSize(9.5);const ls=split(doc,o.observacoes,180);doc.text(ls,14,y);y+=ls.length*5+5}
    if(y>250){doc.addPage();y=20}doc.setTextColor(...dark);doc.setFontSize(10);if(o.subtotal!=null){doc.text(`Subtotal: ${moneyBR(o.subtotal)}`,196,y,{align:'right'});y+=6}if(o.recebimento==='entrega'&&o.taxa_entrega!=null){doc.text(`Entrega: ${moneyBR(o.taxa_entrega)}`,196,y,{align:'right'});y+=6}doc.setTextColor(...red);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text(`TOTAL: ${moneyBR(o.total)}`,196,y+4,{align:'right'});doc.save(`pedido-${safe(o.id).replace(/[^a-zA-Z0-9_-]/g,'_')}.pdf`)}
  function enhance(rows){lastOrders=rows||[];setTimeout(()=>{const table=document.querySelector('#ordersTable table');if(!table)return;const h=table.querySelector('thead tr');if(h&&!h.querySelector('[data-pdf-head]')){const th=document.createElement('th');th.dataset.pdfHead='1';th.textContent='PDF';h.appendChild(th)}table.querySelectorAll('tbody tr').forEach((tr,idx)=>{if(tr.querySelector('[data-order-pdf]'))return;const td=document.createElement('td');const b=document.createElement('button');b.type='button';b.dataset.orderPdf=String(idx);b.textContent='📄 PDF';b.className='primary';b.onclick=async()=>{b.disabled=true;b.textContent='Gerando...';try{await makeOrderPdf(lastOrders[idx])}catch(e){alert('Não foi possível gerar o PDF deste pedido: '+e.message)}finally{b.disabled=false;b.textContent='📄 PDF'}};td.appendChild(b);tr.appendChild(td)})},0)}
  function hook(){if(typeof window.renderOrders!=='function')return false;const base=window.renderOrders;window.renderOrders=function(rows){const r=base(rows);enhance(rows);return r};return true}
  function autoRefresh(){setInterval(()=>{if(document.hidden)return;const panel=document.getElementById('panel');if(panel?.hidden)return;if(typeof window.loadReport==='function')window.loadReport().catch(()=>{})},5000)}
  if(!hook()){let n=0;const t=setInterval(()=>{if(hook()||++n>30)clearInterval(t)},200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',autoRefresh,{once:true});else autoRefresh();
})();